services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - "FLASK_ENV=development"
      - "FLASK_DEBUG=1"
    develop:
      watch:
        - action: sync
          path: ./web
          target: /code
  redis:
    image: "redis:alpine"