services:
  usb-playground:
    build: ./usb-playground
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - "./usb-playground:/app"
    privileged: true