services:
  ros2-dev:
    build: .
    container_name: ros2-dev
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - "/home/luke/workspace/boxfish:/app/boxfish"
      - "/home/luke/.rviz2:/app/.rviz2"
      - "/opt:/opt:ro"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw" 
    privileged: true
    restart: unless-stopped
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
      - DISPLAY=${DISPLAY} # On host: run "xhost +"
      - QT_X11_NO_MITSHM=1  
