services:
  ros2-dev:
    build: .
    container_name: ros2-dev
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - "/home/anyone/boxfish:/app"
      - "/opt/pylon:/opt/pylon:ro"
    privileged: true

